### ISSUE TITLE
The `pageSize` is ignored when `orderBy` is set to `NftOrdering.TRANSFERTIME`

### ISSUE THREAD

**Issue by taeguk** [alchemyplatform/alchemy-sdk-js#282]
### [REQUIRED] Environment

- Alchemy SDK version: 2.6.0

### [REQUIRED] Describe the problem

In `getContractsForOwner` and `getNftsForOwner`, the `pageSize` is ignored when `orderBy` is set to `NftOrdering.TRANSFERTIME`.

#### Relevant code or sample repro:
This works well:
```typescript
this.alchemy.nft.getNftsForOwner(walletAddress, {
      contractAddresses,
      pageSize,
      pageKey,
    });
```

But this ignores `pageSize`:
```typescript
this.alchemy.nft.getNftsForOwner(walletAddress, {
      contractAddresses,
      orderBy: NftOrdering.TRANSFERTIME,
      pageSize,
      pageKey,
    });
```

**Comment by taeguk** [comment]
It happens again for `getNftsForOwner`

**Comment by taeguk** [comment]
@thebrianchen It happens again for `getNftsForOwner`

**Comment by taeguk** [comment]
It still happens.

**Comment by taeguk** [comment]
* url : https://eth-mainnet.g.alchemy.com/nft/v2/{apiKey}/getNFTs

**Comment by taeguk** [comment]
@thebrianchen excuse me, how was it going?

**Comment by taeguk** [comment]
@thebrianchen ping because our product will be release soon and we need it. 🙏

**Comment by thebrianchen** [comment]
@taeguk Missed this message. I will investigate this next week

**Comment by thebrianchen** [comment]
@taeguk This is now fixed.

**Comment by taeguk** [comment]
@thebrianchen it still happens when `contractAddresses` are not empty.
here it is the reproduce:
* url : https://eth-mainnet.g.alchemy.com/nft/v2/{apiKey}/getNFTs
* params
  * owner : 0xf96A5d6c20872a7DdCacdDE4e825249040250d66
  * contractAddresses : [0x84162fe2e695fedbf4d3bca1c3458fb616e44735]
  * orderBy : transferTime
  * pageSize : 10

**Comment by thebrianchen** [comment]
@taeguk This URL is working fine for me: 
`https://eth-mainnet.g.alchemy.com/nft/v2/your-api-key/getNFTs?owner=0xf96A5d6c20872a7DdCacdDE4e825249040250d66&orderBy=transferTime&pageSize=10&contractAddresses%5B%5D=0x84162fe2e695fedbf4d3bca1c3458fb616e44735`
